PROGS_DIAMONDFOLD_OBJS := diamondfold.o
PROGS_DIAMONDFOLD_OBJS := $(PROGS_DIAMONDFOLD_OBJS:%=$(TDIR)/diamondfold/%)
ALL_OBJS += $(PROGS_DIAMONDFOLD_OBJS)

$(TDIR)/bin/diamondfold : $(TSTART) $(PROGS_DIAMONDFOLD_OBJS) $(TLIBC)

